server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d8esehojs32c738pflbg-a.oregon-postgres.render.com:5432/hospital_wnvd
spring.datasource.username=hospital_user
spring.datasource.password=QTHo0qoWQS8HcTtl17iy0gYk2rgeqqUx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect